import type { ProviderCatalogEntry } from "../types.ts";

export const CLOUD_CN: ProviderCatalogEntry[] = [
  {
    id: "deepseek",
    label: "DeepSeek (深度求索)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.deepseek.com",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPrefix: "sk-",
    keyPlaceholder: "sk-...",
    docsUrl: "https://platform.deepseek.com/api_keys",
    envVar: "DEEPSEEK_API_KEY",
    defaultModels: [
      { id: "deepseek-chat", label: "DeepSeek Chat (V3)", capabilities: ["tools"] },
      { id: "deepseek-reasoner", label: "DeepSeek Reasoner (R1)", capabilities: ["reasoning"] },
    ],
  },
  {
    id: "qwen",
    label: "通义千问 (Qwen / DashScope)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPrefix: "sk-",
    keyPlaceholder: "sk-...",
    docsUrl: "https://dashscope.console.aliyun.com/apiKey",
    envVar: "DASHSCOPE_API_KEY",
    defaultModels: [
      { id: "qwen-max", label: "Qwen Max", capabilities: ["tools"] },
      { id: "qwen-plus", label: "Qwen Plus", capabilities: ["tools"] },
      { id: "qwen-turbo", label: "Qwen Turbo", capabilities: ["tools"] },
      { id: "qwen-long", label: "Qwen Long (1M ctx)", capabilities: ["tools"] },
    ],
  },
  {
    id: "zhipu",
    label: "智谱 AI (GLM)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    envVar: "ZHIPU_API_KEY",
    defaultModels: [
      { id: "glm-4-plus", label: "GLM-4 Plus", capabilities: ["tools"] },
      { id: "glm-4-flash", label: "GLM-4 Flash", capabilities: ["tools"] },
      { id: "glm-4-long", label: "GLM-4 Long (1M ctx)", capabilities: ["tools"] },
    ],
  },
  {
    id: "moonshot",
    label: "月之暗面 (Kimi)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.moonshot.cn/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPrefix: "sk-",
    keyPlaceholder: "sk-...",
    docsUrl: "https://platform.moonshot.cn/console/api-keys",
    envVar: "MOONSHOT_API_KEY",
    defaultModels: [
      { id: "moonshot-v1-128k", label: "Moonshot V1 128K", capabilities: ["tools"] },
      { id: "moonshot-v1-32k", label: "Moonshot V1 32K", capabilities: ["tools"] },
      { id: "moonshot-v1-8k", label: "Moonshot V1 8K", capabilities: ["tools"] },
    ],
  },
  {
    id: "baichuan",
    label: "百川智能 (Baichuan)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.baichuan-ai.com/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://platform.baichuan-ai.com/console/apikey",
    envVar: "BAICHUAN_API_KEY",
    defaultModels: [
      { id: "Baichuan4", label: "Baichuan 4", capabilities: ["tools"] },
      { id: "Baichuan3-Turbo", label: "Baichuan 3 Turbo", capabilities: ["tools"] },
    ],
  },
  {
    id: "minimax",
    label: "MiniMax (海螺 AI)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.minimax.chat/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    envVar: "MINIMAX_API_KEY",
    defaultModels: [{ id: "MiniMax-Text-01", label: "MiniMax Text 01", capabilities: ["tools"] }],
  },
  {
    id: "stepfun",
    label: "阶跃星辰 (StepFun)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.stepfun.com/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://platform.stepfun.com/interface-key",
    envVar: "STEPFUN_API_KEY",
    defaultModels: [
      { id: "step-2-16k", label: "Step 2 16K", capabilities: ["tools"] },
      { id: "step-1-128k", label: "Step 1 128K", capabilities: ["tools"] },
    ],
  },
  {
    id: "yi",
    label: "零一万物 (Yi / Lingyiwanwu)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.lingyiwanwu.com/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://platform.lingyiwanwu.com/apikeys",
    envVar: "YI_API_KEY",
    defaultModels: [
      { id: "yi-lightning", label: "Yi Lightning", capabilities: ["tools"] },
      { id: "yi-large", label: "Yi Large", capabilities: ["tools"] },
    ],
  },
  {
    id: "doubao",
    label: "豆包 (ByteDance / 火山引擎)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    envVar: "ARK_API_KEY",
    defaultModels: [
      { id: "doubao-pro-32k", label: "豆包 Pro 32K", capabilities: ["tools"] },
      { id: "doubao-lite-32k", label: "豆包 Lite 32K", capabilities: ["tools"] },
    ],
    notes:
      "Model IDs are endpoint IDs (ep-xxx) created in Volcano Engine console, not fixed model names.",
  },
  {
    id: "spark",
    label: "讯飞星火 (Spark)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://spark-api-open.xf-yun.com/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://console.xfyun.cn/services/bm35",
    envVar: "SPARK_API_KEY",
    defaultModels: [
      { id: "generalv3.5", label: "Spark 3.5", capabilities: ["tools"] },
      { id: "4.0Ultra", label: "Spark 4.0 Ultra", capabilities: ["tools"] },
    ],
    notes: "API key format: appid:apisecret. See iFlytek docs for details.",
  },
  {
    id: "hunyuan",
    label: "腾讯混元 (Hunyuan)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://console.cloud.tencent.com/cam/capi",
    envVar: "HUNYUAN_API_KEY",
    defaultModels: [
      { id: "hunyuan-pro", label: "Hunyuan Pro", capabilities: ["tools"] },
      { id: "hunyuan-standard", label: "Hunyuan Standard", capabilities: ["tools"] },
    ],
  },
  {
    id: "siliconflow",
    label: "硅基流动 (SiliconFlow)",
    region: "cn",
    category: "cloud",
    defaultBaseUrl: "https://api.siliconflow.cn/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPrefix: "sk-",
    keyPlaceholder: "sk-...",
    docsUrl: "https://cloud.siliconflow.cn/account/ak",
    envVar: "SILICONFLOW_API_KEY",
    defaultModels: [
      { id: "deepseek-ai/DeepSeek-V3", label: "DeepSeek V3", capabilities: ["tools"] },
      { id: "Qwen/Qwen2.5-72B-Instruct", label: "Qwen 2.5 72B", capabilities: ["tools"] },
      { id: "deepseek-ai/DeepSeek-R1", label: "DeepSeek R1", capabilities: ["reasoning"] },
    ],
    notes: "Aggregator — hosts many open-source models. Model IDs use org/model format.",
  },
];
