import type { ProviderCatalogEntry } from "../types.ts";

export const CLOUD_GLOBAL: ProviderCatalogEntry[] = [
  {
    id: "openai",
    label: "OpenAI",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.openai.com/v1",
    defaultApi: "openai-responses",
    authMode: "api-key",
    keyPrefix: "sk-",
    keyPlaceholder: "sk-proj-...",
    docsUrl: "https://platform.openai.com/api-keys",
    envVar: "OPENAI_API_KEY",
    defaultModels: [
      { id: "gpt-4o", label: "GPT-4o", capabilities: ["vision", "tools"] },
      { id: "gpt-4o-mini", label: "GPT-4o Mini", capabilities: ["vision", "tools"] },
      { id: "gpt-4.1", label: "GPT-4.1", capabilities: ["vision", "tools"] },
      { id: "gpt-4.1-mini", label: "GPT-4.1 Mini", capabilities: ["vision", "tools"] },
      { id: "gpt-4.1-nano", label: "GPT-4.1 Nano", capabilities: ["tools"] },
      { id: "o3-mini", label: "o3-mini", capabilities: ["reasoning", "tools"] },
    ],
  },
  {
    id: "anthropic",
    label: "Anthropic",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.anthropic.com",
    defaultApi: "anthropic-messages",
    authMode: "api-key",
    keyPrefix: "sk-ant-",
    keyPlaceholder: "sk-ant-api03-...",
    docsUrl: "https://console.anthropic.com/settings/keys",
    envVar: "ANTHROPIC_API_KEY",
    defaultModels: [
      {
        id: "claude-sonnet-4-20250514",
        label: "Claude Sonnet 4",
        capabilities: ["vision", "tools"],
      },
      { id: "claude-3-5-haiku-20241022", label: "Claude 3.5 Haiku", capabilities: ["tools"] },
    ],
  },
  {
    id: "google",
    label: "Google AI (Gemini)",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultApi: "google-generative-ai",
    authMode: "api-key",
    keyPrefix: "AIza",
    keyPlaceholder: "AIza...",
    docsUrl: "https://aistudio.google.com/apikey",
    envVar: "GOOGLE_API_KEY",
    defaultModels: [
      {
        id: "gemini-2.5-pro",
        label: "Gemini 2.5 Pro",
        capabilities: ["vision", "tools", "reasoning"],
      },
      { id: "gemini-2.5-flash", label: "Gemini 2.5 Flash", capabilities: ["vision", "tools"] },
      { id: "gemini-2.0-flash", label: "Gemini 2.0 Flash", capabilities: ["vision", "tools"] },
    ],
  },
  {
    id: "groq",
    label: "Groq",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPrefix: "gsk_",
    keyPlaceholder: "gsk_...",
    docsUrl: "https://console.groq.com/keys",
    envVar: "GROQ_API_KEY",
    defaultModels: [
      { id: "llama-3.3-70b-versatile", label: "Llama 3.3 70B", capabilities: ["tools"] },
      { id: "gemma2-9b-it", label: "Gemma2 9B", capabilities: ["tools"] },
    ],
  },
  {
    id: "together",
    label: "Together AI",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.together.xyz/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://api.together.ai/settings/api-keys",
    envVar: "TOGETHER_API_KEY",
    defaultModels: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        label: "Llama 3.3 70B Turbo",
        capabilities: ["tools"],
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct-Turbo",
        label: "Qwen 2.5 72B Turbo",
        capabilities: ["tools"],
      },
    ],
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "fw_...",
    docsUrl: "https://fireworks.ai/account/api-keys",
    envVar: "FIREWORKS_API_KEY",
    defaultModels: [
      {
        id: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        label: "Llama 3.3 70B",
        capabilities: ["tools"],
      },
    ],
  },
  {
    id: "mistral",
    label: "Mistral AI",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.mistral.ai/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://console.mistral.ai/api-keys",
    envVar: "MISTRAL_API_KEY",
    defaultModels: [
      { id: "mistral-large-latest", label: "Mistral Large", capabilities: ["vision", "tools"] },
      { id: "mistral-small-latest", label: "Mistral Small", capabilities: ["tools"] },
      { id: "codestral-latest", label: "Codestral", capabilities: ["tools"] },
    ],
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPrefix: "sk-or-",
    keyPlaceholder: "sk-or-...",
    docsUrl: "https://openrouter.ai/keys",
    envVar: "OPENROUTER_API_KEY",
    defaultModels: [
      { id: "openai/gpt-4o", label: "GPT-4o (via OpenRouter)", capabilities: ["vision", "tools"] },
      {
        id: "anthropic/claude-sonnet-4",
        label: "Claude Sonnet 4 (via OpenRouter)",
        capabilities: ["vision", "tools"],
      },
    ],
    notes: "Aggregator — routes to many providers. Model IDs use provider/model format.",
  },
  {
    id: "cohere",
    label: "Cohere",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.cohere.com/v2",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://dashboard.cohere.com/api-keys",
    envVar: "COHERE_API_KEY",
    defaultModels: [
      { id: "command-r-plus", label: "Command R+", capabilities: ["tools"] },
      { id: "command-r", label: "Command R", capabilities: ["tools"] },
    ],
  },
  {
    id: "sambanova",
    label: "SambaNova",
    region: "global",
    category: "cloud",
    defaultBaseUrl: "https://api.sambanova.ai/v1",
    defaultApi: "openai-completions",
    authMode: "api-key",
    keyPlaceholder: "...",
    docsUrl: "https://cloud.sambanova.ai/apis",
    envVar: "SAMBANOVA_API_KEY",
    defaultModels: [
      { id: "Meta-Llama-3.3-70B-Instruct", label: "Llama 3.3 70B", capabilities: ["tools"] },
      { id: "DeepSeek-R1", label: "DeepSeek R1", capabilities: ["reasoning"] },
    ],
  },
];
