import type { ProviderCatalogEntry } from "../types.ts";

export const LOCAL: ProviderCatalogEntry[] = [
  {
    id: "ollama",
    label: "Ollama",
    region: "local",
    category: "local",
    defaultBaseUrl: "http://localhost:11434/v1",
    defaultApi: "openai-completions",
    authMode: "none",
    docsUrl: "https://ollama.com/library",
    defaultModels: [],
    notes: "Models auto-discovered via Ollama API. Pull models with: ollama pull <model>",
  },
  {
    id: "lmstudio",
    label: "LM Studio",
    region: "local",
    category: "local",
    defaultBaseUrl: "http://localhost:1234/v1",
    defaultApi: "openai-completions",
    authMode: "none",
    docsUrl: "https://lmstudio.ai",
    defaultModels: [],
    notes: "Start a local server in LM Studio, then models are auto-discovered.",
  },
  {
    id: "vllm",
    label: "vLLM",
    region: "local",
    category: "local",
    defaultBaseUrl: "http://localhost:8000/v1",
    defaultApi: "openai-completions",
    authMode: "none",
    docsUrl: "https://docs.vllm.ai",
    defaultModels: [],
    notes:
      "Model depends on vLLM launch args: python -m vllm.entrypoints.openai.api_server --model <model>",
  },
  {
    id: "llamacpp",
    label: "llama.cpp (server)",
    region: "local",
    category: "local",
    defaultBaseUrl: "http://localhost:8080/v1",
    defaultApi: "openai-completions",
    authMode: "none",
    docsUrl: "https://github.com/ggml-org/llama.cpp/blob/master/examples/server/README.md",
    defaultModels: [],
    notes: "Start with: llama-server -m <model.gguf> --port 8080",
  },
  {
    id: "sglang",
    label: "SGLang",
    region: "local",
    category: "local",
    defaultBaseUrl: "http://localhost:30000/v1",
    defaultApi: "openai-completions",
    authMode: "none",
    docsUrl: "https://sgl-project.github.io",
    defaultModels: [],
    notes: "Start with: python -m sglang.launch_server --model-path <model> --port 30000",
  },
  {
    id: "localai",
    label: "LocalAI",
    region: "local",
    category: "local",
    defaultBaseUrl: "http://localhost:8080/v1",
    defaultApi: "openai-completions",
    authMode: "none",
    docsUrl: "https://localai.io",
    defaultModels: [],
    notes: "Community-driven local inference. Supports GGUF, transformers, and more.",
  },
];
